entities:
- name: deployment_component

  properties:
  - name: name
    type: string
    primary_key: true

  - name: type
    type: string
    subtype_key: true

  relationships:
  - name: node
    reference_entity_name: deployment_node
    cardinality: "1"
    inherited: true