entities:
- name: deployment_node

  properties:
  - name: name
    type: string
    primary_key: true
    example_values:
    - main_cluster

  - name: type
    type: string
    subtype_key: true
    example_values:
    - gke_cluster

  - name: domain_name
    type: string
    optional: true
    default_value: |
      "example.com"

  - name: acme_name
    type: string
    optional: true

  relationships:
  - name: environment
    reference_entity_name: deployment_environment
    cardinality: "1"
    reverse_of: nodes
    inherited: true

  - name: components
    reference_entity_name: deployment_component
    cardinality: "*"
    aggregate: true

  - name: clients
    reference_entity_name: client_component
    cardinality: "*"
    snippet: |
      components.filter{ it is ClientComponent } as List<ClientComponent>

  - name: services
    reference_entity_name: service_component
    cardinality: "*"
    snippet: |
      components.filter{ it is ServiceComponent } as List<ServiceComponent>

  - name: datastores
    reference_entity_name: datastore_component
    cardinality: "*"
    snippet: |
      components.filter{ it is DatastoreComponent } as List<DatastoreComponent>

  - name: acme
    reference_entity_name: acme
    cardinality: "0..1"
    mappings:
    - from: acme_name
      to: name
