entities:
- name: environment
  namespace: laplacian.arch.deployment

  properties:
  - name: name
    type: string
    primary_key: true

  - name: tier
    type: string
    domain:
      choices:
      - value: local
      - value: development
      - value: staging
      - value: production

  - name: uses_locally_built_container_images
    type: boolean
    optional: true
    default_value: |
      listOf("development", "local").any{ it == tier }

  relationships:
  - name: deployments
    cardinality: "*"
    reference_entity_name: deployment
    aggregate: true

  - name: components
    cardinality: "*"
    reference_entity_name: component
    snippet: |
      deployments.map{ it.component }.distinct()

