entities:
- name: postgres_container_deployment
  namespace: laplacian.arch.deployment.component.postgres
  supertype_name: db_container_deployment
  supertype_namespace: laplacian.arch.deployment.container

  properties:
  - name: port
    type: number
    optional: true
    default_value: |
      5432
